export const reviews = [
    // --- Food Reviews (targetType: 'Food') ---
    {
        _id: "60c72b8f9f1b4c3e8a4a5b6d",
        targetId: 'F-Biri-901',
        targetType: 'Food',
        orderId: 'ORD-58932',
        rating: 4,
        comment: 'Excellent biryani, but slightly less spicy than I hoped for. The rice texture was perfect and the meat was very tender, but for a true Dhal Puri experience, I need a stronger kick of chili.',
        user: {
            id: 'user-id-001',
            name: 'Md Sakib',
            email: "sakib@gmail.com",
            image: 'https://placehold.co/550x550/444444/ff7800.png?text=S',
        },
        restaurantId: 'R-DHK-456',
        createdAt: new Date("2025-09-29T10:00:00.000Z"),
        isHidden: false,
    },
    {
        _id: "60c72b8f9f1b4c3e8a4a5b6f",
        targetId: 'F-Pizza-002',
        targetType: 'Food',
        orderId: 'ORD-58933',
        rating: 5,
        comment: 'The best thin-crust pizza I have had in the city! The toppings were generous, and the cheese pull was phenomenal. My family and I will definitely be ordering this again next weekend.',
        user: {
            id: 'user-id-002',
            name: 'Nusrat Jahan',
            email: "nusrat@example.com",
            image: 'https://placehold.co/550x550/444444/ff7800.png?text=N',
        },
        restaurantId: 'R-CHT-123',
        createdAt: new Date("2025-09-29T11:15:00.000Z"),
        isHidden: false,
    },
    {
        _id: "60c72b8f9f1b4c3e8a4a5b70",
        targetId: 'F-Kebab-555',
        targetType: 'Food',
        orderId: 'ORD-58934',
        rating: 3,
        comment: 'The kebab was too dry. Good flavor, but needs more marinade to keep it juicy. It was edible, but certainly didn\'t meet my expectations for the price point.',
        user: {
            id: 'user-id-003',
            name: 'Kamal Hossain',
            email: "kamal@example.com",
            image: 'https://placehold.co/550x550/444444/ff7800.png?text=K',
        },
        restaurantId: 'R-DHK-456',
        createdAt: new Date("2025-09-29T12:30:00.000Z"),
        isHidden: false,
    },
    {
        _id: "60c72b8f9f1b4c3e8a4a5b71",
        targetId: 'F-Burger-111',
        targetType: 'Food',
        orderId: 'ORD-58935',
        rating: 5,
        comment: 'Classic juicy burger. Highly recommend this food! Everything from the bun to the special sauce was fresh and delicious. It arrived hot, which is a big bonus for delivery.',
        user: {
            id: 'user-id-004',
            name: 'Fariha Akter',
            email: "fariha@example.com",
            image: 'https://placehold.co/550x550/444444/ff7800.png?text=F',
        },
        restaurantId: 'R-RAJ-789',
        createdAt: new Date("2025-09-29T13:45:00.000Z"),
        isHidden: false,
    },
    {
        _id: "60c72b8f9f1b4c3e8a4a5b72",
        targetId: 'F-Dessert-009',
        targetType: 'Food',
        orderId: 'ORD-58936',
        rating: 2,
        comment: 'The sweet was sour and tasted old. I was very disappointed that the dessert was not fresh. I had to throw it away, which is a waste of money.',
        user: {
            id: 'user-id-005',
            name: 'Jahidul Islam',
            email: "jahidul@example.com",
            image: 'https://placehold.co/550x550/444444/ff7800.png?text=J',
        },
        restaurantId: 'R-DHK-456',
        createdAt: new Date("2025-09-29T15:00:00.000Z"),
        isHidden: true,
    },

    // --- Rider Reviews (targetType: 'Rider') ---
    {
        _id: "60c72b8f9f1b4c3e8a4a5b73",
        targetId: 'Rider-ID-101',
        targetType: 'Rider',
        orderId: 'ORD-58933',
        rating: 5,
        comment: 'Very professional and polite. The rider called me immediately after arriving and waited patiently. Delivered my food extremely fast and was courteous upon handover!',
        user: {
            id: 'user-id-002',
            name: 'Towhid Islam',
            email: "tawhid@gmail.com",
            image: 'https://placehold.co/550x550/444444/ff7800.png?text=T',
        },
        createdAt: new Date("2025-09-29T11:20:00.000Z"),
        isHidden: false,
    },
    {
        _id: "60c72b8f9f1b4c3e8a4a5b74",
        targetId: 'Rider-ID-202',
        targetType: 'Rider',
        orderId: 'ORD-58935',
        rating: 4,
        comment: 'Friendly service, but the route was a bit slow due to unexpected traffic delays downtown. Still, the rider was apologetic and the food was intact.',
        user: {
            id: 'user-id-004',
            name: 'Rana Mia',
            email: "rana@example.com",
            image: 'https://placehold.co/550x550/444444/ff7800.png?text=R',
        },
        createdAt: new Date("2025-09-29T13:50:00.000Z"),
        isHidden: false,
    },
    {
        _id: "60c72b8f9f1b4c3e8a4a5b75",
        targetId: 'Rider-ID-303',
        targetType: 'Rider',
        orderId: 'ORD-58937',
        rating: 5,
        comment: 'Delivered food hot and fresh, excellent job maintaining temperature and ensuring the package was sealed securely. This is the quality service I expect from FastFest.',
        user: {
            id: 'user-id-006',
            name: 'Shakil Ahmed',
            email: "shakil@example.com",
            image: 'https://placehold.co/550x550/444444/ff7800.png?text=S',
        },
        createdAt: new Date("2025-09-29T16:00:00.000Z"),
        isHidden: false,
    },
    {
        _id: "60c72b8f9f1b4c3e8a4a5b76",
        targetId: 'Rider-ID-101',
        targetType: 'Rider',
        orderId: 'ORD-58938',
        rating: 1,
        comment: 'Rider forgot to check the full order against the receipt. A critical side dish was missing, which ruined the dinner. Please train your riders to verify every item before leaving.',
        user: {
            id: 'user-id-007',
            name: 'Ayesha Begum',
            email: "ayesha@example.com",
            image: 'https://placehold.co/550x550/444444/ff7800.png?text=A',
        },
        createdAt: new Date("2025-09-29T17:30:00.000Z"),
        isHidden: false,
    },
    {
        _id: "60c72b8f9f1b4c3e8a4a5b77",
        targetId: 'Rider-ID-404',
        targetType: 'Rider',
        orderId: 'ORD-58939',
        rating: 3,
        comment: 'Average delivery experience. The rider was neither particularly fast nor slow, and did not make contact with me directly.',
        user: {
            id: 'user-id-008',
            name: 'Babul Haque',
            email: "babul@example.com",
            image: 'https://placehold.co/550x550/444444/ff7800.png?text=B',
        },
        createdAt: new Date("2025-09-29T18:45:00.000Z"),
        isHidden: false,
    },

    // --- Restaurant Reviews (targetType: 'Restaurant') ---
    {
        _id: "60c72b8f9f1b4c3e8a4a5b78",
        targetId: 'R-DHK-456',
        targetType: 'Restaurant',
        orderId: 'ORD-58932',
        rating: 4,
        comment: 'Food was great, but the kitchen preparation time was a little slow, delaying the overall delivery. I appreciate the food quality though, fantastic recipe!',
        user: {
            id: 'user-id-001',
            name: 'Md Rakib',
            email: "rakib@gmail.com",
            image: 'https://placehold.co/550x550/444444/ff7800.png?text=R',
        },
        createdAt: new Date("2025-09-29T10:05:00.000Z"),
        isHidden: false,
    },
    {
        _id: "60c72b8f9f1b4c3e8a4a5b79",
        targetId: 'R-CHT-123',
        targetType: 'Restaurant',
        orderId: 'ORD-58933',
        rating: 5,
        comment: 'This restaurant serves very good food. The packaging was immaculate, and the order was completely accurate. Highly recommended for family dinners!',
        user: {
            id: 'user-id-002',
            name: 'Nusrat Jahan',
            email: "nusrat@example.com",
            image: 'https://placehold.co/550x550/444444/ff7800.png?text=N',
        },
        createdAt: new Date("2025-09-29T11:30:00.000Z"),
        isHidden: false,
    },
    {
        _id: "60c72b8f9f1b4c3e8a4a5b7a",
        targetId: 'R-RAJ-789',
        targetType: 'Restaurant',
        orderId: 'ORD-58935',
        rating: 5,
        comment: 'Amazing service and very fresh ingredients. My favorite spot because they are consistently excellent and always follow my special instructions perfectly.',
        user: {
            id: 'user-id-004',
            name: 'Fariha Akter',
            email: "fariha@example.com",
            image: 'https://placehold.co/550x550/444444/ff7800.png?text=F',
        },
        createdAt: new Date("2025-09-29T14:00:00.000Z"),
        isHidden: false,
    },
    {
        _id: "60c72b8f9f1b4c3e8a4a5b7b",
        targetId: 'R-KHL-333',
        targetType: 'Restaurant',
        orderId: 'ORD-58940',
        rating: 2,
        comment: 'The order was completely wrong. Poor attention to detail, and the items we received were cold. We had to call the restaurant directly to resolve the issue, which took too long.',
        user: {
            id: 'user-id-009',
            name: 'Sumiya Khan',
            email: "sumiya@example.com",
            image: 'https://placehold.co/550x550/444444/ff7800.png?text=S',
        },
        createdAt: new Date("2025-09-29T19:00:00.000Z"),
        isHidden: false,
    },
    {
        _id: "60c72b8f9f1b4c3e8a4a5b7c",
        targetId: 'R-DHK-456',
        targetType: 'Restaurant',
        orderId: 'ORD-58934',
        rating: 3,
        comment: 'Decent food, but the packaging was messy and slightly damaged upon arrival. The restaurant needs to improve how they secure their takeout boxes.',
        user: {
            id: 'user-id-003',
            name: 'Kamal Hossain',
            email: "kamal@example.com",
            image: 'https://placehold.co/550x550/444444/ff7800.png?text=K',
        },
        createdAt: new Date("2025-09-29T12:40:00.000Z"),
        isHidden: false,
    },

    // --- Mixed Reviews (Further examples) ---
    {
        _id: "60c72b8f9f1b4c3e8a4a5b7d",
        targetId: 'F-Burger-111',
        targetType: 'Food',
        orderId: 'ORD-58941',
        rating: 4,
        comment: 'Good size and value for money! This burger is definitely one of the best value items on the menu at this restaurant.',
        user: {
            id: 'user-id-010',
            name: 'Nasir Uddin',
            email: "nasir@example.com",
            image: 'https://placehold.co/550x550/444444/ff7800.png?text=N',
        },
        restaurantId: 'R-RAJ-789',
        createdAt: new Date("2025-09-30T09:15:00.000Z"),
        isHidden: false,
    },
    {
        _id: "60c72b8f9f1b4c3e8a4a5b7e",
        targetId: 'Rider-ID-303',
        targetType: 'Rider',
        orderId: 'ORD-58941',
        rating: 5,
        comment: 'Fastest delivery I have ever received! Great work from the rider, who was professional and navigated the morning traffic flawlessly to get the order here quickly.',
        user: {
            id: 'user-id-010',
            name: 'Nasir Uddin',
            email: "nasir@example.com",
            image: 'https://placehold.co/550x550/444444/ff7800.png?text=N',
        },
        createdAt: new Date("2025-09-30T09:20:00.000Z"),
        isHidden: false,
    },
    {
        _id: "60c72b8f9f1b4c3e8a4a5b7f",
        targetId: 'R-RAJ-789',
        targetType: 'Restaurant',
        orderId: 'ORD-58941',
        rating: 4,
        comment: 'Solid menu options and reliable quality every time. I appreciate their consistency with portion sizes and ingredient freshness.',
        user: {
            id: 'user-id-010',
            name: 'Nasir Uddin',
            email: "nasir@example.com",
            image: 'https://placehold.co/550x550/444444/ff7800.png?text=N',
        },
        createdAt: new Date("2025-09-30T09:25:00.000Z"),
        isHidden: false,
    },
    {
        _id: "60c72b8f9f1b4c3e8a4a5b80",
        targetId: 'Rider-ID-404',
        targetType: 'Rider',
        orderId: 'ORD-58942',
        rating: 2,
        comment: 'The rider was 20 minutes late and didn\'t apologize or notify me of the delay, which was very frustrating as I was waiting.',
        user: {
            id: 'user-id-011',
            name: 'Khadija Islam',
            email: "khadija@example.com",
            image: 'https://placehold.co/550x550/444444/ff7800.png?text=K',
        },
        createdAt: new Date("2025-09-30T10:00:00.000Z"),
        isHidden: false,
    },
    {
        _id: "60c72b8f9f1b4c3e8a4a5b81",
        targetId: 'R-KHL-333',
        targetType: 'Restaurant',
        orderId: 'ORD-58943',
        rating: 4,
        comment: 'Happy with the service, very clean food preparation, and the ingredients tasted high-quality. Will definitely order from here again soon.',
        user: {
            id: 'user-id-012',
            name: 'Anisul Haque',
            email: "anisul@example.com",
            image: 'https://placehold.co/550x550/444444/ff7800.png?text=A',
        },
        createdAt: new Date("2025-09-30T10:30:00.000Z"),
        isHidden: false,
    }
]