const rawProducts = [
  {
    _id: "60c72b2f9f1b2c001f3e4d5e",
    imageUrl: "https://i.ibb.co/WNrqbBhy/Classic-Tom-Yum-Soup.jpg",
    title: "Classic Tom Yum Soup",
    description:
      "Traditional Thai hot and sour soup with shrimp, mushrooms, lemongrass, and kaffir lime leaves.",
    price: 320,
    offerPrice: 256, // 20% discount
    discountRate: 20,
    isCombo: false,
    cuisine: "Thai",
    category: "Soups",
    rating: 4.7,
    ingredients: [
      "Shrimp",
      "Mushrooms",
      "Lemongrass",
      "Kaffir Lime",
      "Chili",
      "Lime Juice",
    ],
    dietaryTags: ["Gluten-Free", "Pescatarian"],
    availability: true,
    restaurantId: "60c72b2f9f1b2c001f3e4d60",
    createdAt: "2025-09-29T10:00:00.000Z",
  },
  {
    _id: "60c72b2f9f1b2c001f3e4d5f",
    imageUrl: "https://i.ibb.co/FLv26TdP/Authentic-Pad-Thai.jpg",
    title: "Authentic Pad Thai",
    description:
      "Stir-fried rice noodles with tofu, shrimp, bean sprouts, peanuts, and tamarind sauce.",
    price: 380,
    offerPrice: 266, // 30% discount
    discountRate: 30,
    isCombo: true,
    cuisine: "Thai",
    category: "Noodles",
    rating: 4.5,
    ingredients: [
      "Rice Noodles",
      "Tofu",
      "Shrimp",
      "Bean Sprouts",
      "Peanuts",
      "Tamarind",
    ],
    dietaryTags: ["Contains Nuts", "Pescatarian"],
    availability: true,
    restaurantId: "60c72b2f9f1b2c001f3e4d60",
    createdAt: "2025-09-29T10:05:00.000Z",
  },
  {
    _id: "60c72b2f9f1b2c001f3e4d61",
    imageUrl: "https://i.ibb.co/5XJ2tZdQ/Thai-Green-Curry.jpg",
    title: "Thai Green Curry",
    description:
      "Aromatic curry with coconut milk, Thai basil, eggplant, and your choice of protein.",
    price: 420,
    offerPrice: 336, // 20% discount
    discountRate: 20,
    isCombo: false,
    cuisine: "Thai",
    category: "Snacks",
    rating: 4.8,
    ingredients: [
      "Coconut Milk",
      "Green Curry Paste",
      "Thai Basil",
      "Eggplant",
      "Chicken",
      "Bamboo Shoots",
    ],
    dietaryTags: ["Dairy-Free", "Spicy"],
    availability: true,
    restaurantId: "60c72b2f9f1b2c001f3e4d60",
    createdAt: "2025-09-29T10:10:00.000Z",
  },
  {
    _id: "60c72b2f9f1b2c001f3e4d62",
    imageUrl: "https://i.ibb.co/4zHZ6SN/Mango-Sticky-Rice.jpg",
    title: "Mango Sticky Rice",
    description:
      "Sweet coconut sticky rice topped with fresh mango slices and sesame seeds.",
    price: 220,
    offerPrice: 176, // 20% discount
    discountRate: 20,
    isCombo: false,
    cuisine: "Thai",
    category: "Cakes",
    rating: 4.9,
    ingredients: [
      "Sticky Rice",
      "Coconut Milk",
      "Mango",
      "Sugar",
      "Sesame Seeds",
    ],
    dietaryTags: ["Vegetarian", "Dessert"],
    availability: true,
    restaurantId: "60c72b2f9f1b2c001f3e4d60",
    createdAt: "2025-09-29T10:15:00.000Z",
  },
  {
    _id: "60c72b2f9f1b2c001f3e4d63",
    imageUrl: "https://i.ibb.co/GX35bJf/Som-Tum-Papaya-Salad.jpg",
    title: "Som Tum (Papaya Salad)",
    description:
      "Spicy green papaya salad with tomatoes, beans, peanuts, and lime dressing.",
    price: 280,
    offerPrice: 224, // 20% discount
    discountRate: 20,
    isCombo: false,
    cuisine: "Thai",
    category: "Snacks",
    rating: 4.6,
    ingredients: [
      "Green Papaya",
      "Tomato",
      "Green Beans",
      "Peanuts",
      "Lime",
      "Chili",
    ],
    dietaryTags: ["Vegan", "Gluten-Free", "Spicy"],
    availability: true,
    restaurantId: "60c72b2f9f1b2c001f3e4d60",
    createdAt: "2025-09-29T10:20:00.000Z",
  },
  {
    _id: "60c72b2f9f1b2c001f3e4d64",
    imageUrl: "https://i.ibb.co/Psx2Jg93/Massaman-Curry.jpg",
    title: "Massaman Curry",
    description:
      "Rich and mild curry with potatoes, onions, peanuts, and tender beef.",
    price: 450,
    offerPrice: 315, // 30% discount
    discountRate: 30,
    isCombo: true,
    cuisine: "Thai",
    category: "Snacks",
    rating: 4.7,
    ingredients: [
      "Beef",
      "Potato",
      "Onion",
      "Peanuts",
      "Coconut Milk",
      "Massaman Curry Paste",
    ],
    dietaryTags: ["Contains Nuts", "Dairy-Free"],
    availability: true,
    restaurantId: "60c72b2f9f1b2c001f3e4d60",
    createdAt: "2025-09-29T10:25:00.000Z",
  },
  {
    _id: "60c72b2f9f1b2c001f3e4d65",
    imageUrl: "https://i.ibb.co/7NXyKkbz/Fresh-Spring-Rolls.jpg",
    title: "Fresh Spring Rolls",
    description:
      "Rice paper rolls filled with vegetables, herbs, and served with sweet chili sauce.",
    price: 250,
    offerPrice: 200, // 20% discount
    discountRate: 20,
    isCombo: false,
    cuisine: "Thai",
    category: "Snacks",
    rating: 4.4,
    ingredients: [
      "Rice Paper",
      "Lettuce",
      "Carrot",
      "Cucumber",
      "Mint",
      "Basil",
    ],
    dietaryTags: ["Vegan", "Gluten-Free"],
    availability: true,
    restaurantId: "60c72b2f9f1b2c001f3e4d60",
    createdAt: "2025-09-29T10:30:00.000Z",
  },
  {
    _id: "60c72b2f9f1b2c001f3e4d66",
    imageUrl: "https://i.ibb.co/ksdjTGD2/Chicken-Satay.jpg",
    title: "Chicken Satay",
    description:
      "Grilled chicken skewers marinated in Thai spices, served with peanut sauce.",
    price: 320,
    offerPrice: 256, // 20% discount
    discountRate: 20,
    isCombo: true,
    cuisine: "Thai",
    category: "Kebab",
    rating: 4.6,
    ingredients: [
      "Chicken",
      "Peanut Sauce",
      "Turmeric",
      "Lemongrass",
      "Cumin",
      "Coriander",
    ],
    dietaryTags: ["Contains Nuts", "High-Protein"],
    availability: true,
    restaurantId: "60c72b2f9f1b2c001f3e4d60",
    createdAt: "2025-09-29T10:35:00.000Z",
  },
  {
    _id: "60c72b2f9f1b2c001f3e4d67",
    imageUrl: "https://i.ibb.co/2QMCJ1J/Thai-Fish-Cakes.jpg",
    title: "Thai Fish Cakes",
    description:
      "Crispy fish cakes with red curry paste, green beans, and sweet chili sauce.",
    price: 350,
    offerPrice: 280, // 20% discount
    discountRate: 20,
    isCombo: false,
    cuisine: "Thai",
    category: "Snacks",
    rating: 4.5,
    ingredients: [
      "Fish",
      "Red Curry Paste",
      "Green Beans",
      "Lime Leaves",
      "Egg",
      "Flour",
    ],
    dietaryTags: ["Pescatarian", "Spicy"],
    availability: true,
    restaurantId: "60c72b2f9f1b2c001f3e4d60",
    createdAt: "2025-09-29T10:40:00.000Z",
  },
  {
    _id: "60c72b2f9f1b2c001f3e4d68",
    imageUrl: "https://i.ibb.co/YFcKX1dz/Coconut-Chicken-Soup.jpg",
    title: "Coconut Chicken Soup",
    description:
      "Creamy coconut soup with chicken, mushrooms, galangal, and lime juice.",
    price: 340,
    offerPrice: 238, // 30% discount
    discountRate: 30,
    isCombo: false,
    cuisine: "Thai",
    category: "Soups",
    rating: 4.7,
    ingredients: [
      "Coconut Milk",
      "Chicken",
      "Mushrooms",
      "Galangal",
      "Lime Juice",
      "Chili",
    ],
    dietaryTags: ["Dairy-Free", "Spicy"],
    availability: true,
    restaurantId: "60c72b2f9f1b2c001f3e4d60",
    createdAt: "2025-09-29T10:45:00.000Z",
  },
  {
    _id: "60c72b2f9f1b2c001f3e4d69",
    imageUrl: "https://i.ibb.co/bjdpDMqm/Spaghetti-Carbonara.jpg",
    title: "Spaghetti Carbonara",
    description: "Creamy pasta with eggs, cheese, pancetta, and black pepper.",
    price: 420,
    offerPrice: 336, // 20% discount
    discountRate: 20,
    isCombo: true,
    cuisine: "Italian",
    category: "Pasta",
    rating: 4.7,
    ingredients: [
      "Spaghetti",
      "Eggs",
      "Pecorino Romano",
      "Pancetta",
      "Black Pepper",
    ],
    dietaryTags: ["Contains Pork", "High-Protein"],
    availability: true,
    restaurantId: "60c72b2f9f1b2c001f3e4d61",
    createdAt: "2025-09-29T11:05:00.000Z",
  },
  {
    _id: "60c72b2f9f1b2c001f3e4d6a",
    imageUrl: "https://i.ibb.co/sdMs3yGQ/Classic-Tiramisu.jpg",
    title: "Classic Tiramisu",
    description:
      "Traditional Italian dessert with coffee-soaked ladyfingers and mascarpone cream.",
    price: 280,
    offerPrice: 196, // 30% discount
    discountRate: 30,
    isCombo: false,
    cuisine: "Italian",
    category: "Cakes",
    rating: 4.9,
    ingredients: [
      "Ladyfingers",
      "Mascarpone",
      "Coffee",
      "Cocoa",
      "Eggs",
      "Sugar",
    ],
    dietaryTags: ["Contains Caffeine", "Dessert"],
    availability: true,
    restaurantId: "60c72b2f9f1b2c001f3e4d61",
    createdAt: "2025-09-29T11:10:00.000Z",
  },
  {
    _id: "60c72b2f9f1b2c001f3e4d6b",
    imageUrl: "https://i.ibb.co/WNrqbBhy/Classic-Tom-Yum-Soup.jpg",
    title: "Classic Tom Yum Soup",
    description:
      "Traditional Thai hot and sour soup with shrimp, mushrooms, lemongrass, and kaffir lime leaves.",
    price: 320,
    offerPrice: 256, // 20% discount
    discountRate: 20,
    isCombo: false,
    cuisine: "Thai",
    category: "Soups",
    rating: 4.7,
    ingredients: [
      "Shrimp",
      "Mushrooms",
      "Lemongrass",
      "Kaffir Lime",
      "Chili",
      "Lime Juice",
    ],
    dietaryTags: ["Gluten-Free", "Pescatarian"],
    availability: true,
    restaurantId: "60c72b2f9f1b2c001f3e4d60",
    createdAt: "2025-09-29T10:00:00.000Z",
  },
  {
    _id: "60c72b2f9f1b2c001f3e4d6c",
    imageUrl: "https://i.ibb.co/FLv26TdP/Authentic-Pad-Thai.jpg",
    title: "Authentic Pad Thai",
    description:
      "Stir-fried rice noodles with tofu, shrimp, bean sprouts, peanuts, and tamarind sauce.",
    price: 380,
    offerPrice: 266, // 30% discount
    discountRate: 30,
    isCombo: true,
    cuisine: "Thai",
    category: "Noodles",
    rating: 4.5,
    ingredients: [
      "Rice Noodles",
      "Tofu",
      "Shrimp",
      "Bean Sprouts",
      "Peanuts",
      "Tamarind",
    ],
    dietaryTags: ["Contains Nuts", "Pescatarian"],
    availability: true,
    restaurantId: "60c72b2f9f1b2c001f3e4d60",
    createdAt: "2025-09-29T10:05:00.000Z",
  },
  {
    _id: "60c72b2f9f1b2c001f3e4d6d",
    imageUrl: "https://i.ibb.co/5XJ2tZdQ/Thai-Green-Curry.jpg",
    title: "Thai Green Curry",
    description:
      "Aromatic curry with coconut milk, Thai basil, eggplant, and your choice of protein.",
    price: 420,
    offerPrice: 336, // 20% discount
    discountRate: 20,
    isCombo: false,
    cuisine: "Thai",
    category: "Snacks",
    rating: 4.8,
    ingredients: [
      "Coconut Milk",
      "Green Curry Paste",
      "Thai Basil",
      "Eggplant",
      "Chicken",
      "Bamboo Shoots",
    ],
    dietaryTags: ["Dairy-Free", "Spicy"],
    availability: true,
    restaurantId: "60c72b2f9f1b2c001f3e4d60",
    createdAt: "2025-09-29T10:10:00.000Z",
  },
  {
    _id: "60c72b2f9f1b2c001f3e4d6e",
    imageUrl: "https://i.ibb.co/4zHZ6SN/Mango-Sticky-Rice.jpg",
    title: "Mango Sticky Rice",
    description:
      "Sweet coconut sticky rice topped with fresh mango slices and sesame seeds.",
    price: 220,
    offerPrice: 176, // 20% discount
    discountRate: 20,
    isCombo: false,
    cuisine: "Thai",
    category: "Cakes",
    rating: 4.9,
    ingredients: [
      "Sticky Rice",
      "Coconut Milk",
      "Mango",
      "Sugar",
      "Sesame Seeds",
    ],
    dietaryTags: ["Vegetarian", "Dessert"],
    availability: true,
    restaurantId: "60c72b2f9f1b2c001f3e4d60",
    createdAt: "2025-09-29T10:15:00.000Z",
  },
  {
    _id: "60c72b2f9f1b2c001f3e4d6f",
    imageUrl: "https://i.ibb.co/GX35bJf/Som-Tum-Papaya-Salad.jpg",
    title: "Som Tum (Papaya Salad)",
    description:
      "Spicy green papaya salad with tomatoes, beans, peanuts, and lime dressing.",
    price: 280,
    offerPrice: 224, // 20% discount
    discountRate: 20,
    isCombo: false,
    cuisine: "Thai",
    category: "Snacks",
    rating: 4.6,
    ingredients: [
      "Green Papaya",
      "Tomato",
      "Green Beans",
      "Peanuts",
      "Lime",
      "Chili",
    ],
    dietaryTags: ["Vegan", "Gluten-Free", "Spicy"],
    availability: true,
    restaurantId: "60c72b2f9f1b2c001f3e4d60",
    createdAt: "2025-09-29T10:20:00.000Z",
  },
  {
    _id: "60c72b2f9f1b2c001f3e4d70",
    imageUrl: "https://i.ibb.co/Psx2Jg93/Massaman-Curry.jpg",
    title: "Massaman Curry",
    description:
      "Rich and mild curry with potatoes, onions, peanuts, and tender beef.",
    price: 450,
    offerPrice: 315, // 30% discount
    discountRate: 30,
    isCombo: true,
    cuisine: "Thai",
    category: "Snacks",
    rating: 4.7,
    ingredients: [
      "Beef",
      "Potato",
      "Onion",
      "Peanuts",
      "Coconut Milk",
      "Massaman Curry Paste",
    ],
    dietaryTags: ["Contains Nuts", "Dairy-Free"],
    availability: true,
    restaurantId: "60c72b2f9f1b2c001f3e4d60",
    createdAt: "2025-09-29T10:25:00.000Z",
  },
  {
    _id: "60c72b2f9f1b2c001f3e4d71",
    imageUrl: "https://i.ibb.co/7NXyKkbz/Fresh-Spring-Rolls.jpg",
    title: "Fresh Spring Rolls",
    description:
      "Rice paper rolls filled with vegetables, herbs, and served with sweet chili sauce.",
    price: 250,
    offerPrice: 200, // 20% discount
    discountRate: 20,
    isCombo: false,
    cuisine: "Thai",
    category: "Snacks",
    rating: 4.4,
    ingredients: [
      "Rice Paper",
      "Lettuce",
      "Carrot",
      "Cucumber",
      "Mint",
      "Basil",
    ],
    dietaryTags: ["Vegan", "Gluten-Free"],
    availability: true,
    restaurantId: "60c72b2f9f1b2c001f3e4d60",
    createdAt: "2025-09-29T10:30:00.000Z",
  },
  {
    _id: "60c72b2f9f1b2c001f3e4d72",
    imageUrl: "https://i.ibb.co/ksdjTGD2/Chicken-Satay.jpg",
    title: "Chicken Satay",
    description:
      "Grilled chicken skewers marinated in Thai spices, served with peanut sauce.",
    price: 320,
    offerPrice: 256, // 20% discount
    discountRate: 20,
    isCombo: true,
    cuisine: "Thai",
    category: "Kebab",
    rating: 4.6,
    ingredients: [
      "Chicken",
      "Peanut Sauce",
      "Turmeric",
      "Lemongrass",
      "Cumin",
      "Coriander",
    ],
    dietaryTags: ["Contains Nuts", "High-Protein"],
    availability: true,
    restaurantId: "60c72b2f9f1b2c001f3e4d60",
    createdAt: "2025-09-29T10:35:00.000Z",
  },
  {
    _id: "60c72b2f9f1b2c001f3e4d73",
    imageUrl: "https://i.ibb.co/2QMCJ1J/Thai-Fish-Cakes.jpg",
    title: "Thai Fish Cakes",
    description:
      "Crispy fish cakes with red curry paste, green beans, and sweet chili sauce.",
    price: 350,
    offerPrice: 280, // 20% discount
    discountRate: 20,
    isCombo: false,
    cuisine: "Thai",
    category: "Snacks",
    rating: 4.5,
    ingredients: [
      "Fish",
      "Red Curry Paste",
      "Green Beans",
      "Lime Leaves",
      "Egg",
      "Flour",
    ],
    dietaryTags: ["Pescatarian", "Spicy"],
    availability: true,
    restaurantId: "60c72b2f9f1b2c001f3e4d60",
    createdAt: "2025-09-29T10:40:00.000Z",
  },
  {
    _id: "60c72b2f9f1b2c001f3e4d74",
    imageUrl: "https://i.ibb.co/YFcKX1dz/Coconut-Chicken-Soup.jpg",
    title: "Coconut Chicken Soup",
    description:
      "Creamy coconut soup with chicken, mushrooms, galangal, and lime juice.",
    price: 340,
    offerPrice: 238, // 30% discount
    discountRate: 30,
    isCombo: false,
    cuisine: "Thai",
    category: "Soups",
    rating: 4.7,
    ingredients: [
      "Coconut Milk",
      "Chicken",
      "Mushrooms",
      "Galangal",
      "Lime Juice",
      "Chili",
    ],
    dietaryTags: ["Dairy-Free", "Spicy"],
    availability: true,
    restaurantId: "60c72b2f9f1b2c001f3e4d60",
    createdAt: "2025-09-29T10:45:00.000Z",
  },
  {
    _id: "60c72b2f9f1b2c001f3e4d75",
    imageUrl: "https://i.ibb.co/bjdpDMqm/Spaghetti-Carbonara.jpg",
    title: "Spaghetti Carbonara",
    description: "Creamy pasta with eggs, cheese, pancetta, and black pepper.",
    price: 420,
    offerPrice: 336, // 20% discount
    discountRate: 20,
    isCombo: true,
    cuisine: "Italian",
    category: "Pasta",
    rating: 4.7,
    ingredients: [
      "Spaghetti",
      "Eggs",
      "Pecorino Romano",
      "Pancetta",
      "Black Pepper",
    ],
    dietaryTags: ["Contains Pork", "High-Protein"],
    availability: true,
    restaurantId: "60c72b2f9f1b2c001f3e4d61",
    createdAt: "2025-09-29T11:05:00.000Z",
  },
  {
    _id: "60c72b2f9f1b2c001f3e4d76",
    imageUrl: "https://i.ibb.co/sdMs3yGQ/Classic-Tiramisu.jpg",
    title: "Classic Tiramisu",
    description:
      "Traditional Italian dessert with coffee-soaked ladyfingers and mascarpone cream.",
    price: 280,
    offerPrice: 196, // 30% discount
    discountRate: 30,
    isCombo: false,
    cuisine: "Italian",
    category: "Cakes",
    rating: 4.9,
    ingredients: [
      "Ladyfingers",
      "Mascarpone",
      "Coffee",
      "Cocoa",
      "Eggs",
      "Sugar",
    ],
    dietaryTags: ["Contains Caffeine", "Dessert"],
    availability: true,
    restaurantId: "60c72b2f9f1b2c001f3e4d61",
    createdAt: "2025-09-29T11:10:00.000Z",
  },
  {
    _id: "60c72b2f9f1b2c001f3e4d77",
    imageUrl: "https://i.ibb.co/WNrqbBhy/Classic-Tom-Yum-Soup.jpg",
    title: "Classic Tom Yum Soup",
    description:
      "Traditional Thai hot and sour soup with shrimp, mushrooms, lemongrass, and kaffir lime leaves.",
    price: 320,
    offerPrice: 224, // 30% discount
    discountRate: 30,
    isCombo: false,
    cuisine: "Thai",
    category: "Soups",
    rating: 4.7,
    ingredients: [
      "Shrimp",
      "Mushrooms",
      "Lemongrass",
      "Kaffir Lime",
      "Chili",
      "Lime Juice",
    ],
    dietaryTags: ["Gluten-Free", "Pescatarian"],
    availability: true,
    restaurantId: "60c72b2f9f1b2c001f3e4d60",
    createdAt: "2025-09-29T10:00:00.000Z",
  },
  {
    _id: "60c72b2f9f1b2c001f3e4d78",
    imageUrl: "https://i.ibb.co/FLv26TdP/Authentic-Pad-Thai.jpg",
    title: "Authentic Pad Thai",
    description:
      "Stir-fried rice noodles with tofu, shrimp, bean sprouts, peanuts, and tamarind sauce.",
    price: 380,
    offerPrice: 304, // 20% discount
    discountRate: 20,
    isCombo: true,
    cuisine: "Thai",
    category: "Noodles",
    rating: 4.5,
    ingredients: [
      "Rice Noodles",
      "Tofu",
      "Shrimp",
      "Bean Sprouts",
      "Peanuts",
      "Tamarind",
    ],
    dietaryTags: ["Contains Nuts", "Pescatarian"],
    availability: true,
    restaurantId: "60c72b2f9f1b2c001f3e4d60",
    createdAt: "2025-09-29T10:05:00.000Z",
  },
  {
    _id: "60c72b2f9f1b2c001f3e4d79",
    imageUrl: "https://i.ibb.co/5XJ2tZdQ/Thai-Green-Curry.jpg",
    title: "Thai Green Curry",
    description:
      "Aromatic curry with coconut milk, Thai basil, eggplant, and your choice of protein.",
    price: 420,
    offerPrice: 294, // 30% discount
    discountRate: 30,
    isCombo: false,
    cuisine: "Thai",
    category: "Snacks",
    rating: 4.8,
    ingredients: [
      "Coconut Milk",
      "Green Curry Paste",
      "Thai Basil",
      "Eggplant",
      "Chicken",
      "Bamboo Shoots",
    ],
    dietaryTags: ["Dairy-Free", "Spicy"],
    availability: true,
    restaurantId: "60c72b2f9f1b2c001f3e4d60",
    createdAt: "2025-09-29T10:10:00.000Z",
  },
  {
    _id: "60c72b2f9f1b2c001f3e4d7a",
    imageUrl: "https://i.ibb.co/4zHZ6SN/Mango-Sticky-Rice.jpg",
    title: "Mango Sticky Rice",
    description:
      "Sweet coconut sticky rice topped with fresh mango slices and sesame seeds.",
    price: 220,
    offerPrice: 154, // 30% discount
    discountRate: 30,
    isCombo: false,
    cuisine: "Thai",
    category: "Cakes",
    rating: 4.9,
    ingredients: [
      "Sticky Rice",
      "Coconut Milk",
      "Mango",
      "Sugar",
      "Sesame Seeds",
    ],
    dietaryTags: ["Vegetarian", "Dessert"],
    availability: true,
    restaurantId: "60c72b2f9f1b2c001f3e4d60",
    createdAt: "2025-09-29T10:15:00.000Z",
  },
  {
    _id: "60c72b2f9f1b2c001f3e4d7b",
    imageUrl: "https://i.ibb.co/GX35bJf/Som-Tum-Papaya-Salad.jpg",
    title: "Som Tum (Papaya Salad)",
    description:
      "Spicy green papaya salad with tomatoes, beans, peanuts, and lime dressing.",
    price: 280,
    offerPrice: 196, // 30% discount
    discountRate: 30,
    isCombo: false,
    cuisine: "Thai",
    category: "Snacks",
    rating: 4.6,
    ingredients: [
      "Green Papaya",
      "Tomato",
      "Green Beans",
      "Peanuts",
      "Lime",
      "Chili",
    ],
    dietaryTags: ["Vegan", "Gluten-Free", "Spicy"],
    availability: true,
    restaurantId: "60c72b2f9f1b2c001f3e4d60",
    createdAt: "2025-09-29T10:20:00.000Z",
  },
  {
    _id: "60c72b2f9f1b2c001f3e4d7c",
    imageUrl: "https://i.ibb.co/Psx2Jg93/Massaman-Curry.jpg",
    title: "Massaman Curry",
    description:
      "Rich and mild curry with potatoes, onions, peanuts, and tender beef.",
    price: 450,
    offerPrice: 360, // 20% discount
    discountRate: 20,
    isCombo: true,
    cuisine: "Thai",
    category: "Snacks",
    rating: 4.7,
    ingredients: [
      "Beef",
      "Potato",
      "Onion",
      "Peanuts",
      "Coconut Milk",
      "Massaman Curry Paste",
    ],
    dietaryTags: ["Contains Nuts", "Dairy-Free"],
    availability: true,
    restaurantId: "60c72b2f9f1b2c001f3e4d60",
    createdAt: "2025-09-29T10:25:00.000Z",
  },
  {
    _id: "60c72b2f9f1b2c001f3e4d7d",
    imageUrl: "https://i.ibb.co/7NXyKkbz/Fresh-Spring-Rolls.jpg",
    title: "Fresh Spring Rolls",
    description:
      "Rice paper rolls filled with vegetables, herbs, and served with sweet chili sauce.",
    price: 250,
    offerPrice: 175, // 30% discount
    discountRate: 30,
    isCombo: false,
    cuisine: "Thai",
    category: "Snacks",
    rating: 4.4,
    ingredients: [
      "Rice Paper",
      "Lettuce",
      "Carrot",
      "Cucumber",
      "Mint",
      "Basil",
    ],
    dietaryTags: ["Vegan", "Gluten-Free"],
    availability: true,
    restaurantId: "60c72b2f9f1b2c001f3e4d60",
    createdAt: "2025-09-29T10:30:00.000Z",
  },
  {
    _id: "60c72b2f9f1b2c001f3e4d7e",
    imageUrl: "https://i.ibb.co/ksdjTGD2/Chicken-Satay.jpg",
    title: "Chicken Satay",
    description:
      "Grilled chicken skewers marinated in Thai spices, served with peanut sauce.",
    price: 320,
    offerPrice: 224, // 30% discount
    discountRate: 30,
    isCombo: true,
    cuisine: "Thai",
    category: "Kebab",
    rating: 4.6,
    ingredients: [
      "Chicken",
      "Peanut Sauce",
      "Turmeric",
      "Lemongrass",
      "Cumin",
      "Coriander",
    ],
    dietaryTags: ["Contains Nuts", "High-Protein"],
    availability: true,
    restaurantId: "60c72b2f9f1b2c001f3e4d60",
    createdAt: "2025-09-29T10:35:00.000Z",
  },
  {
    _id: "60c72b2f9f1b2c001f3e4d7f",
    imageUrl: "https://i.ibb.co/2QMCJ1J/Thai-Fish-Cakes.jpg",
    title: "Thai Fish Cakes",
    description:
      "Crispy fish cakes with red curry paste, green beans, and sweet chili sauce.",
    price: 350,
    offerPrice: 245, // 30% discount
    discountRate: 30,
    isCombo: false,
    cuisine: "Thai",
    category: "Snacks",
    rating: 4.5,
    ingredients: [
      "Fish",
      "Red Curry Paste",
      "Green Beans",
      "Lime Leaves",
      "Egg",
      "Flour",
    ],
    dietaryTags: ["Pescatarian", "Spicy"],
    availability: true,
    restaurantId: "60c72b2f9f1b2c001f3e4d60",
    createdAt: "2025-09-29T10:40:00.000Z",
  },
  {
    _id: "60c72b2f9f1b2c001f3e4d80",
    imageUrl: "https://i.ibb.co/YFcKX1dz/Coconut-Chicken-Soup.jpg",
    title: "Coconut Chicken Soup",
    description:
      "Creamy coconut soup with chicken, mushrooms, galangal, and lime juice.",
    price: 340,
    offerPrice: 272, // 20% discount
    discountRate: 20,
    isCombo: false,
    cuisine: "Thai",
    category: "Soups",
    rating: 4.7,
    ingredients: [
      "Coconut Milk",
      "Chicken",
      "Mushrooms",
      "Galangal",
      "Lime Juice",
      "Chili",
    ],
    dietaryTags: ["Dairy-Free", "Spicy"],
    availability: true,
    restaurantId: "60c72b2f9f1b2c001f3e4d60",
    createdAt: "2025-09-29T10:45:00.000Z",
  },
  {
    _id: "60c72b2f9f1b2c001f3e4d81",
    imageUrl: "https://i.ibb.co/bjdpDMqm/Spaghetti-Carbonara.jpg",
    title: "Spaghetti Carbonara",
    description: "Creamy pasta with eggs, cheese, pancetta, and black pepper.",
    price: 420,
    offerPrice: 294, // 30% discount
    discountRate: 30,
    isCombo: true,
    cuisine: "Italian",
    category: "Pasta",
    rating: 4.7,
    ingredients: [
      "Spaghetti",
      "Eggs",
      "Pecorino Romano",
      "Pancetta",
      "Black Pepper",
    ],
    dietaryTags: ["Contains Pork", "High-Protein"],
    availability: true,
    restaurantId: "60c72b2f9f1b2c001f3e4d61",
    createdAt: "2025-09-29T11:05:00.000Z",
  },
  {
    _id: "60c72b2f9f1b2c001f3e4d82",
    imageUrl: "https://i.ibb.co/sdMs3yGQ/Classic-Tiramisu.jpg",
    title: "Classic Tiramisu",
    description:
      "Traditional Italian dessert with coffee-soaked ladyfingers and mascarpone cream.",
    price: 280,
    offerPrice: 224, // 20% discount
    discountRate: 20,
    isCombo: false,
    cuisine: "Italian",
    category: "Cakes",
    rating: 4.9,
    ingredients: [
      "Ladyfingers",
      "Mascarpone",
      "Coffee",
      "Cocoa",
      "Eggs",
      "Sugar",
    ],
    dietaryTags: ["Contains Caffeine", "Dessert"],
    availability: true,
    restaurantId: "60c72b2f9f1b2c001f3e4d61",
    createdAt: "2025-09-29T11:10:00.000Z",
  },
];

export default rawProducts;
