export const restaurants = [
  {
    id: "rest_001",
    slug: "kacchi-bhai-dhanmondi",
    name: "Kacchi Bhai",
    logo: "https://i.ibb.co.com/1YFN5k3C/kacchi-bhai-2-logo.png",
    banner:
      "https://bestlistbd.com/wp-content/uploads/classified-listing/2021/09/177534213_311121510627014_6362311441237242299_n.jpg",
    rating: 4.6,
    reviewsCount: 128,
    cuisines: ["Bengali", "Biriyani"],
    priceRange: "৳৳",
    estimatedDeliveryTime: "30-40 min",
    deliveryFee: 30,
    isFeatured: true,
    isActive: true,
    approved: true,
    ownerId: "user_rest_01",
    location: {
      address: "House 12/A, Road 5, Dhanmondi",
      area: "Dhanmondi",
      city: "Dhaka",
      country: "Bangladesh",
      coordinates: { lat: 23.7465, lng: 90.376 },
    },
    contact: {
      phone: "01710000001",
      email: "info@kacchibhai.bd",
    },
    openingHours: {
      mon: "10:00-23:00",
      tue: "10:00-23:00",
      wed: "10:00-23:00",
      thu: "10:00-23:00",
      fri: "10:00-00:00",
      sat: "10:00-00:00",
      sun: "10:00-22:00",
    },
    menuPreview: [
      { id: "m_kb_01", name: "Kacchi Biriyani", price: 250 },
      { id: "m_kb_02", name: "Borhani", price: 60 },
      { id: "m_kb_03", name: "Mixed Kabab Platter", price: 320 },
    ],
    menu: [
      {
        id: "m_kb_01",
        name: "Kacchi Biriyani",
        description:
          "Traditional slow-cooked mutton biriyani with saffron and spices.",
        price: 250,
        category: "Main",
        image: "https://i.ibb.co.com/BFYbKRr/download-2.jpg",
        massUnit: "plate",
        isAvailable: true,
      },
      {
        id: "m_kb_02",
        name: "Borhani",
        description: "Spiced yogurt drink, perfect with biriyani.",
        price: 60,
        category: "Beverage",
        image: "https://i.ibb.co.com/N23Vq5gc/download-3.jpg",
        massUnit: "cup",
        isAvailable: true,
      },
      {
        id: "m_kb_03",
        name: "Mixed Kabab Platter",
        description: "Chicken & beef kababs served with naan and chutney.",
        price: 320,
        category: "Share",
        image: "/images/menu/mixed-kabab.jpg",
        massUnit: "plate",
        isAvailable: true,
      },
    ],
    stats: {
      totalOrders: 4520,
      monthlyEarnings: 1250000,
    },
    tags: ["Popular", "Family"],
    createdAt: "2025-03-10T09:30:00Z",
    updatedAt: "2025-09-10T12:00:00Z",
  },

  {
    id: "rest_002",
    slug: "pizza-point-gulshan",
    name: "Pizza Point",
    logo: "https://i.ibb.co.com/WWxNbFgt/pizza-point-3.png",
    banner:
      "https://www.fbgcdn.com/pictures/ba4249fb-fde9-4acf-8352-b158850379f9.jpg",
    rating: 4.3,
    reviewsCount: 89,
    cuisines: ["Italian", "Fast Food"],
    priceRange: "৳৳৳",
    estimatedDeliveryTime: "25-35 min",
    deliveryFee: 40,
    isFeatured: false,
    isActive: true,
    approved: true,
    ownerId: "user_rest_02",
    location: {
      address: "House 5, Road 11, Gulshan-2",
      area: "Gulshan",
      city: "Dhaka",
      country: "Bangladesh",
      coordinates: { lat: 23.7925, lng: 90.4078 },
    },
    contact: {
      phone: "01710000002",
      email: "hello@pizzapoint.bd",
    },
    openingHours: {
      mon: "11:00-23:30",
      tue: "11:00-23:30",
      wed: "11:00-23:30",
      thu: "11:00-23:30",
      fri: "11:00-00:30",
      sat: "11:00-00:30",
      sun: "11:00-23:00",
    },
    menuPreview: [
      { id: "m_pp_01", name: "Cheese Pizza (Medium)", price: 450 },
      { id: "m_pp_02", name: "Garlic Bread", price: 150 },
      { id: "m_pp_03", name: "Pepperoni Pizza", price: 520 },
    ],
    menu: [
      {
        id: "m_pp_01",
        name: "Cheese Pizza",
        description:
          "Classic hand-tossed pizza with mozzarella and special sauce.",
        price: 450,
        category: "Pizza",
        image: "/images/menu/cheese-pizza.jpg",
        massUnit: "medium",
        isAvailable: true,
      },
      {
        id: "m_pp_02",
        name: "Garlic Bread",
        description: "Buttery garlic bread, perfect side for pizzas.",
        price: 150,
        category: "Sides",
        image: "/images/menu/garlic-bread.jpg",
        massUnit: "plate",
        isAvailable: true,
      },
      {
        id: "m_pp_03",
        name: "Pepperoni Pizza",
        description: "Loaded with pepperoni and cheese.",
        price: 520,
        category: "Pizza",
        image: "/images/menu/pepperoni-pizza.jpg",
        massUnit: "medium",
        isAvailable: true,
      },
    ],
    stats: {
      totalOrders: 2980,
      monthlyEarnings: 980000,
    },
    tags: ["Fast Delivery", "Hot"],
    createdAt: "2024-11-20T08:15:00Z",
    updatedAt: "2025-09-05T10:00:00Z",
  },

  {
    id: "rest_003",
    slug: "banani-bites",
    name: "Banani Bites",
    logo: "https://i.ibb.co.com/7t409KqN/banani-bites-logo.png",
    banner:
      "https://mybayutcdn.bayut.com/mybayut/wp-content/uploads/Rolla-Sharjah-restaurants-021120.jpg",
    rating: 4.8,
    reviewsCount: 204,
    cuisines: ["Dessert", "Cafe"],
    priceRange: "৳",
    estimatedDeliveryTime: "15-25 min",
    deliveryFee: 0,
    isFeatured: true,
    isActive: true,
    approved: true,
    ownerId: "user_rest_03",
    location: {
      address: "Road 2, Banani",
      area: "Banani",
      city: "Dhaka",
      country: "Bangladesh",
      coordinates: { lat: 23.7929, lng: 90.41 },
    },
    contact: {
      phone: "01710000003",
      email: "contact@bananibites.bd",
    },
    openingHours: {
      mon: "09:00-22:00",
      tue: "09:00-22:00",
      wed: "09:00-22:00",
      thu: "09:00-22:00",
      fri: "09:00-23:00",
      sat: "09:00-23:00",
      sun: "10:00-21:00",
    },
    menuPreview: [
      { id: "m_bb_01", name: "Chocolate Lava Cake", price: 180 },
      { id: "m_bb_02", name: "Cappuccino", price: 120 },
      { id: "m_bb_03", name: "Blueberry Cheesecake", price: 220 },
    ],
    menu: [
      {
        id: "m_bb_01",
        name: "Chocolate Lava Cake",
        description: "Warm molten chocolate with vanilla ice cream.",
        price: 180,
        category: "Dessert",
        image: "/images/menu/lava-cake.jpg",
        massUnit: "piece",
        isAvailable: true,
      },
      {
        id: "m_bb_02",
        name: "Cappuccino",
        description: "Classic espresso-based drink with steamed milk.",
        price: 120,
        category: "Beverage",
        image: "/images/menu/cappuccino.jpg",
        massUnit: "cup",
        isAvailable: true,
      },
      {
        id: "m_bb_03",
        name: "Blueberry Cheesecake",
        description: "Rich cheesecake topped with blueberry compote.",
        price: 220,
        category: "Dessert",
        image: "/images/menu/cheesecake.jpg",
        massUnit: "slice",
        isAvailable: true,
      },
    ],
    stats: {
      totalOrders: 5120,
      monthlyEarnings: 1420000,
    },
    tags: ["Quick", "Low Price"],
    createdAt: "2025-01-05T11:20:00Z",
    updatedAt: "2025-09-12T09:45:00Z",
  },
  {
    id: "rest_004",
    slug: "burger-hub-mirpur",
    name: "Burger Hub",
    logo: "https://i.ibb.co.com/tpHtwyVq/burger-hub-logo.png",
    banner:
      "https://mir-s3-cdn-cf.behance.net/projects/404/774f65184299217.Y3JvcCwxMDgwLDg0NCwwLDExNw.jpg",
    rating: 4.5,
    reviewsCount: 175,
    cuisines: ["Fast Food", "Burgers"],
    priceRange: "৳৳",
    estimatedDeliveryTime: "20-30 min",
    deliveryFee: 25,
    isFeatured: true,
    isActive: true,
    approved: true,
    ownerId: "user_rest_04",
    location: {
      address: "Block B, Section 11, Mirpur",
      area: "Mirpur",
      city: "Dhaka",
      country: "Bangladesh",
      coordinates: { lat: 23.8151, lng: 90.3666 },
    },
    contact: {
      phone: "01710000004",
      email: "support@burgerhub.bd",
    },
    openingHours: {
      mon: "11:00-23:00",
      tue: "11:00-23:00",
      wed: "11:00-23:00",
      thu: "11:00-23:00",
      fri: "11:00-00:00",
      sat: "11:00-00:00",
      sun: "12:00-22:00",
    },
    menuPreview: [
      { id: "m_bh_01", name: "Classic Beef Burger", price: 220 },
      { id: "m_bh_02", name: "Cheese Fries", price: 120 },
      { id: "m_bh_03", name: "Chicken Zinger", price: 200 },
    ],
    menu: [
      {
        id: "m_bh_01",
        name: "Classic Beef Burger",
        description: "Juicy beef patty with lettuce, tomato & sauce.",
        price: 220,
        category: "Burger",
        image: "/images/menu/beef-burger.jpg",
        massUnit: "piece",
        isAvailable: true,
      },
      {
        id: "m_bh_02",
        name: "Cheese Fries",
        description: "Crispy fries topped with melted cheese.",
        price: 120,
        category: "Sides",
        image: "/images/menu/cheese-fries.jpg",
        massUnit: "plate",
        isAvailable: true,
      },
      {
        id: "m_bh_03",
        name: "Chicken Zinger",
        description: "Crispy chicken fillet burger with mayo.",
        price: 200,
        category: "Burger",
        image: "/images/menu/chicken-zinger.jpg",
        massUnit: "piece",
        isAvailable: true,
      },
    ],
    stats: {
      totalOrders: 3780,
      monthlyEarnings: 865000,
    },
    tags: ["Popular", "Spicy"],
    createdAt: "2024-12-10T10:30:00Z",
    updatedAt: "2025-09-15T08:20:00Z",
  },

  {
    id: "rest_005",
    slug: "thai-treats-uttara",
    name: "Time for Thai",
    logo: "https://i.ibb.co.com/Z1LxGTdk/time-for-thai-logo.png",
    banner: "https://www.timeforthai.com.sg/img/timeforthai-mobile.jpg",
    rating: 4.4,
    reviewsCount: 143,
    cuisines: ["Thai", "Asian"],
    priceRange: "৳৳৳",
    estimatedDeliveryTime: "35-45 min",
    deliveryFee: 50,
    isFeatured: false,
    isActive: true,
    approved: true,
    ownerId: "user_rest_05",
    location: {
      address: "Sector 9, Uttara",
      area: "Uttara",
      city: "Dhaka",
      country: "Bangladesh",
      coordinates: { lat: 23.8767, lng: 90.3796 },
    },
    contact: {
      phone: "01710000005",
      email: "info@thaitreats.bd",
    },
    openingHours: {
      mon: "12:00-23:00",
      tue: "12:00-23:00",
      wed: "12:00-23:00",
      thu: "12:00-23:00",
      fri: "13:00-00:00",
      sat: "13:00-00:00",
      sun: "12:00-22:30",
    },
    menuPreview: [
      { id: "m_tt_01", name: "Pad Thai", price: 480 },
      { id: "m_tt_02", name: "Tom Yum Soup", price: 350 },
      { id: "m_tt_03", name: "Thai Green Curry", price: 520 },
    ],
    menu: [
      {
        id: "m_tt_01",
        name: "Pad Thai",
        description: "Stir-fried rice noodles with shrimp and peanuts.",
        price: 480,
        category: "Main",
        image: "/images/menu/pad-thai.jpg",
        massUnit: "plate",
        isAvailable: true,
      },
      {
        id: "m_tt_02",
        name: "Tom Yum Soup",
        description: "Spicy-sour soup with shrimp & herbs.",
        price: 350,
        category: "Soup",
        image: "/images/menu/tom-yum.jpg",
        massUnit: "bowl",
        isAvailable: true,
      },
      {
        id: "m_tt_03",
        name: "Thai Green Curry",
        description: "Coconut milk curry with chicken and vegetables.",
        price: 520,
        category: "Main",
        image: "/images/menu/green-curry.jpg",
        massUnit: "plate",
        isAvailable: true,
      },
    ],
    stats: {
      totalOrders: 2150,
      monthlyEarnings: 645000,
    },
    tags: ["Authentic", "Spicy"],
    createdAt: "2025-02-15T09:45:00Z",
    updatedAt: "2025-09-11T11:10:00Z",
  },

  {
    id: "rest_006",
    slug: "kebab-korner-bashundhara",
    name: "Kebab Korner",
    logo: "https://i.ibb.co.com/m5Dyyhr1/kebab-korner-logo.png",
    banner:
      "https://grub24s3.s3.eu-west-2.amazonaws.com/upload/1663654013-Bg-stevenage.webp",
    rating: 4.2,
    reviewsCount: 97,
    cuisines: ["Middle Eastern", "Grill"],
    priceRange: "৳৳",
    estimatedDeliveryTime: "25-35 min",
    deliveryFee: 30,
    isFeatured: false,
    isActive: true,
    approved: true,
    ownerId: "user_rest_06",
    location: {
      address: "Block C, Bashundhara R/A",
      area: "Bashundhara",
      city: "Dhaka",
      country: "Bangladesh",
      coordinates: { lat: 23.8155, lng: 90.4281 },
    },
    contact: {
      phone: "01710000006",
      email: "order@kebabkorner.bd",
    },
    openingHours: {
      mon: "12:00-23:00",
      tue: "12:00-23:00",
      wed: "12:00-23:00",
      thu: "12:00-23:00",
      fri: "12:00-23:30",
      sat: "12:00-23:30",
      sun: "12:00-22:30",
    },
    menuPreview: [
      { id: "m_kk_01", name: "Beef Seekh Kebab", price: 300 },
      { id: "m_kk_02", name: "Chicken Shawarma", price: 200 },
      { id: "m_kk_03", name: "Falafel Plate", price: 180 },
    ],
    menu: [
      {
        id: "m_kk_01",
        name: "Beef Seekh Kebab",
        description: "Grilled minced beef skewers with spices.",
        price: 300,
        category: "Grill",
        image: "/images/menu/beef-kebab.jpg",
        massUnit: "plate",
        isAvailable: true,
      },
      {
        id: "m_kk_02",
        name: "Chicken Shawarma",
        description: "Tender chicken wrap with garlic sauce.",
        price: 200,
        category: "Wrap",
        image: "/images/menu/shawarma.jpg",
        massUnit: "roll",
        isAvailable: true,
      },
      {
        id: "m_kk_03",
        name: "Falafel Plate",
        description: "Crispy falafels served with hummus.",
        price: 180,
        category: "Veg",
        image: "/images/menu/falafel.jpg",
        massUnit: "plate",
        isAvailable: true,
      },
    ],
    stats: {
      totalOrders: 1670,
      monthlyEarnings: 420000,
    },
    tags: ["Grill", "Halal"],
    createdAt: "2025-03-01T08:30:00Z",
    updatedAt: "2025-09-09T12:25:00Z",
  },

  {
    id: "rest_007",
    slug: "sushi-senpai-banani",
    name: "Sushi Senpai",
    logo: "https://i.ibb.co.com/pBsFLPkd/sushi-senpai-logo.png",
    banner:
      "https://static-content.owner.com/funnel/images/f4710469-8ac4-40dc-a1d0-f6982ca651f8?v=6325200261&w=3840&q=80&auto=format",
    rating: 4.7,
    reviewsCount: 155,
    cuisines: ["Japanese", "Sushi"],
    priceRange: "৳৳৳৳",
    estimatedDeliveryTime: "40-50 min",
    deliveryFee: 60,
    isFeatured: true,
    isActive: true,
    approved: true,
    ownerId: "user_rest_07",
    location: {
      address: "House 20, Road 12, Banani",
      area: "Banani",
      city: "Dhaka",
      country: "Bangladesh",
      coordinates: { lat: 23.7937, lng: 90.4041 },
    },
    contact: {
      phone: "01710000007",
      email: "contact@sushisenpai.bd",
    },
    openingHours: {
      mon: "12:00-22:30",
      tue: "12:00-22:30",
      wed: "12:00-22:30",
      thu: "12:00-22:30",
      fri: "13:00-23:00",
      sat: "13:00-23:00",
      sun: "12:00-21:30",
    },
    menuPreview: [
      { id: "m_ss_01", name: "California Roll", price: 650 },
      { id: "m_ss_02", name: "Salmon Nigiri", price: 550 },
      { id: "m_ss_03", name: "Tempura Udon", price: 700 },
    ],
    menu: [
      {
        id: "m_ss_01",
        name: "California Roll",
        description: "Crab, avocado, cucumber sushi rolls.",
        price: 650,
        category: "Sushi",
        image: "/images/menu/california-roll.jpg",
        massUnit: "8 pcs",
        isAvailable: true,
      },
      {
        id: "m_ss_02",
        name: "Salmon Nigiri",
        description: "Fresh salmon on vinegared rice.",
        price: 550,
        category: "Sushi",
        image: "/images/menu/salmon-nigiri.jpg",
        massUnit: "2 pcs",
        isAvailable: true,
      },
      {
        id: "m_ss_03",
        name: "Tempura Udon",
        description: "Thick wheat noodles with tempura prawns.",
        price: 700,
        category: "Noodles",
        image: "/images/menu/tempura-udon.jpg",
        massUnit: "bowl",
        isAvailable: true,
      },
    ],
    stats: {
      totalOrders: 2450,
      monthlyEarnings: 1180000,
    },
    tags: ["Premium", "Authentic"],
    createdAt: "2025-04-12T09:15:00Z",
    updatedAt: "2025-09-14T11:00:00Z",
  },

  {
    id: "rest_008",
    slug: "roll-express-mohakhali",
    name: "Roll Express",
    logo: "https://i.ibb.co.com/PG8Y7wnm/roll-express-logo.png",
    banner:
      "https://content3.jdmagicbox.com/comp/chandigarh/b9/0172px172.x172.180724182728.e3b9/catalogue/roll-express-chandigarh-sector-36d-chandigarh-fast-food-19mf5tu46g.jpg",
    rating: 4.1,
    reviewsCount: 110,
    cuisines: ["Street Food", "Rolls"],
    priceRange: "৳",
    estimatedDeliveryTime: "15-20 min",
    deliveryFee: 20,
    isFeatured: false,
    isActive: true,
    approved: true,
    ownerId: "user_rest_08",
    location: {
      address: "Mohakhali DOHS Gate",
      area: "Mohakhali",
      city: "Dhaka",
      country: "Bangladesh",
      coordinates: { lat: 23.7805, lng: 90.3982 },
    },
    contact: {
      phone: "01710000008",
      email: "order@rollexpress.bd",
    },
    openingHours: {
      mon: "10:00-22:00",
      tue: "10:00-22:00",
      wed: "10:00-22:00",
      thu: "10:00-22:00",
      fri: "10:00-23:00",
      sat: "10:00-23:00",
      sun: "11:00-21:30",
    },
    menuPreview: [
      { id: "m_re_01", name: "Beef Roll", price: 90 },
      { id: "m_re_02", name: "Chicken Roll", price: 80 },
      { id: "m_re_03", name: "Veg Roll", price: 60 },
    ],
    menu: [
      {
        id: "m_re_01",
        name: "Beef Roll",
        description: "Paratha roll stuffed with spicy beef.",
        price: 90,
        category: "Roll",
        image: "/images/menu/beef-roll.jpg",
        massUnit: "piece",
        isAvailable: true,
      },
      {
        id: "m_re_02",
        name: "Chicken Roll",
        description: "Crispy chicken wrapped in paratha.",
        price: 80,
        category: "Roll",
        image: "/images/menu/chicken-roll.jpg",
        massUnit: "piece",
        isAvailable: true,
      },
      {
        id: "m_re_03",
        name: "Veg Roll",
        description: "Healthy roll with veggies & spices.",
        price: 60,
        category: "Roll",
        image: "/images/menu/veg-roll.jpg",
        massUnit: "piece",
        isAvailable: true,
      },
    ],
    stats: {
      totalOrders: 3200,
      monthlyEarnings: 375000,
    },
    tags: ["Quick", "Budget"],
    createdAt: "2025-03-20T07:50:00Z",
    updatedAt: "2025-09-16T12:40:00Z",
  },
];
