import React from "react";

export const metadata = {
  title: "Blog Page",
  description: "Generated by create next app",
};

export default function page() {
  return (
    <div>
      <h1>Blog Page</h1>
    </div>
  );
}
